### ISSUE TITLE
Remove this unused import ...

### ISSUE THREAD

**Issue by GabrieRabelo** [Stonks-Corp/radardoinvestidor-backend#2]
![image](https://user-images.githubusercontent.com/50777647/163730942-6bbf754f-1bc8-4631-b201-bc3cb6e8c6dc.png)

Remover imports não utilizados na src/controller/funds.ts

**Comment by LucasGCardoso** [comment]
Resolvendo issue através da [PR 9](https://github.com/Stonks-Corp/radardoinvestidor-backend/pull/9)
